name: client_id
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1

environment:
  sdk: ">=3.2.0-174.0.dev <4.0.0"

dependencies:
  adaptive_theme: ^3.6.0
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  path_provider: ^2.0.11
  hydrated_bloc: ^8.1.0
  json_serializable: ^6.5.1
  flutter_bloc: ^8.1.1
  dio: ^5.0.0
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  injectable: ^1.5.3
  get_it: ^7.2.0
  injectable_generator: ^1.5.4

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
